import type { Campaign, Content } from '@/types';
import { tokens } from './brand';
export const photos = {
  hero: '/images/hero.jpg',
  school: '/images/school.jpg',
  food: '/images/food.jpg',
  water: '/images/water.jpg',
  trees: '/images/trees.jpg',
};
const seeds = [
  [
    'a-brighter-start-for-every-child',
    'A brighter start for every child',
    'Education',
    'school',
    'Learning should begin with possibility, not a lack of supplies. Help equip a community classroom.',
    18450,
    25000,
    234,
    'Maya Okafor',
    'Ibadan, Nigeria',
  ],
  [
    'good-food-for-our-neighbors',
    'Good food. Stronger communities.',
    'Food',
    'food',
    'Put fresh, nourishing food on the table for families navigating a difficult season.',
    12800,
    16000,
    186,
    'Daniel Brooks',
    'Bristol, United Kingdom',
  ],
  [
    'clean-water-close-to-home',
    'Clean water, closer to home',
    'Community',
    'water',
    'Help a community repair its shared water point and train a local maintenance team.',
    28750,
    40000,
    412,
    'Amina Bello',
    'Arusha, Tanzania',
  ],
  [
    'a-greener-tomorrow-together',
    'A greener tomorrow starts here',
    'Environment',
    'trees',
    'Support a neighborhood-led tree nursery and restore shade to shared spaces.',
    9600,
    15000,
    143,
    'Lena Martins',
    'Accra, Ghana',
  ],
  [
    'care-without-the-distance',
    'Bring essential care within reach',
    'Healthcare',
    'hero',
    'Equip a mobile care team with everyday supplies and transport for community visits.',
    8200,
    22000,
    98,
    'Noah Mensah',
    'Kumasi, Ghana',
  ],
  [
    'a-safe-start-after-the-storm',
    'A safe start after the storm',
    'Disaster Relief',
    'food',
    'Provide household essentials and practical recovery support for displaced families.',
    19200,
    20000,
    276,
    'Sofia Adeyemi',
    'Lagos, Nigeria',
  ],
  [
    'after-school-full-of-possibility',
    'An afternoon full of possibility',
    'Children',
    'school',
    'Create an accessible after-school space for reading, play, and mentoring.',
    4100,
    10000,
    65,
    'Maya Okafor',
    'Ibadan, Nigeria',
  ],
  [
    'safer-days-for-rescue-animals',
    'Safer days for rescue animals',
    'Animals',
    'trees',
    'Fund shelter repairs and veterinary supplies for a community animal rescue.',
    3600,
    9000,
    72,
    'Lena Martins',
    'Accra, Ghana',
  ],
  [
    'help-families-find-their-feet',
    'Help families find their feet',
    'Emergency Support',
    'hero',
    'Offer time-sensitive essentials and transport to families facing an unexpected crisis.',
    6300,
    12000,
    89,
    'Amina Bello',
    'Arusha, Tanzania',
  ],
] as const;
export const demoCampaigns: Campaign[] = seeds.map((s, i) => ({
  id: `demo-${i + 1}`,
  slug: s[0],
  title: s[1],
  category: s[2],
  coverImage: photos[s[3]],
  shortDescription: s[4],
  description: `## A small act can open a new chapter\n\n${s[4]}\n\nThis fictional campaign illustrates how a community can come together around a practical, achievable goal. Local organizers listen first, plan with their neighbors, and share progress at every step.\n\n## What your support makes possible\n\n- Purchase essential materials from local suppliers\n- Support the people delivering the project\n- Share clear updates on spending and progress\n\n## Staying accountable\n\nThe organizer will publish project updates and an expense summary. Photographs are illustrative stock imagery, not identified beneficiaries of this campaign.`,
  amountRaised: s[5],
  goalAmount: s[6],
  donorCount: s[7],
  organizerName: s[8],
  organizerBio:
    'A fictional community organizer working alongside local volunteers to turn thoughtful plans into practical action.',
  location: s[9],
  organizerId: `demo-organizer-${i % 4}`,
  currency: 'USD',
  gallery: [photos[s[3]]],
  viewCount: s[7] * 8,
  shareCount: s[7] * 2,
  startDate: '2026-08-01',
  endDate: '2027-02-28',
  status: 'approved',
  featured: i < 3,
  verified: true,
  urgent: i === 5,
  createdAt: `2026-08-${String(i + 1).padStart(2, '0')}T00:00:00Z`,
  updatedAt: '2026-09-01T00:00:00Z',
  allocation: [
    { label: 'Project materials', percent: 70 },
    { label: 'Local delivery', percent: 20 },
    { label: 'Reporting & coordination', percent: 10 },
  ],
  searchTokens: tokens(`${s[1]} ${s[2]} ${s[4]} ${s[9]}`),
}));
export const defaultContent: Content = {
  announcement: 'A little kindness can change someone’s whole world.',
  impact: { people: 12400, countries: 12, projects: 86 },
  testimonials: [
    {
      quote: 'For the first time, I could see exactly what my contribution helped make possible.',
      name: 'Alex M.',
      detail: 'Fictional donor story',
    },
    {
      quote: 'Our neighbors brought the idea. This community helped us bring it to life.',
      name: 'Samira K.',
      detail: 'Fictional organizer story',
    },
    {
      quote: 'It is a reminder that you don’t need to do everything to make a real difference.',
      name: 'Jordan R.',
      detail: 'Fictional volunteer story',
    },
  ],
  partners: ['COMMON GROUND', 'the good company', 'evergreen', 'OPEN HANDS', 'together.'],
  faqs: [
    {
      question: 'How are campaigns reviewed?',
      answer:
        'Campaigns are reviewed by our team before publication. A reviewed badge indicates platform approval, not a guarantee of a particular outcome.',
    },
    {
      question: 'Where does my donation go?',
      answer:
        'Your donation supports the campaign you choose. Review its fund allocation and updates for details. Payment processing fees may apply.',
    },
    {
      question: 'Can I give every month?',
      answer:
        'Monthly giving is available through Stripe. You can manage or cancel your subscription from your donor account.',
    },
    {
      question: 'Are donations tax deductible?',
      answer:
        'Tax treatment depends on the receiving organization and your location. A payment receipt is provided; it is not a tax determination.',
    },
  ],
  team: [
    { name: 'Maya Ellis', role: 'Community programs · fictional profile' },
    { name: 'Emeka James', role: 'Trust & transparency · fictional profile' },
    { name: 'Leila Chen', role: 'Volunteer experience · fictional profile' },
  ],
};
